spring:
  redis:
    host: localhost
  datasource:
    url: jdbc:mysql://101.132.110.182:3306/exam?useSSL=false
    username: root
    password: root123

system:
  fdfs-ngix: http://localhost:8888

fdfs:
  tracker-list:
    - localhost:22122
